package runner

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestGraphQLConfig_OOBFlags tests the new --oob-url flag configuration
func TestGraphQLConfig_OOBFlags(t *testing.T) {
	tests := []struct {
		name         string
		enableOOB    bool
		oobURL       string
		oobServer    string
		expectClient bool // Should we create interactsh client?
		expectURL    string
	}{
		{
			name:         "User provides OOB URL",
			enableOOB:    true,
			oobURL:       "http://my-callback.example.com",
			expectClient: false, // No interactsh client needed
			expectURL:    "http://my-callback.example.com",
		},
		{
			name:         "OOB enabled without user URL (legacy interactsh)",
			enableOOB:    true,
			oobURL:       "",
			oobServer:    "oast.live",
			expectClient: true, // Should create interactsh client
			expectURL:    "",   // Will be generated by client
		},
		{
			name:         "OOB disabled",
			enableOOB:    false,
			oobURL:       "",
			expectClient: false,
			expectURL:    "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// We're just testing the flag logic here
			// The actual integration is tested in the template executor

			if tt.oobURL != "" {
				// User provided URL - should NOT need interactsh
				assert.False(t, tt.expectClient)
				assert.Equal(t, tt.expectURL, tt.oobURL)
			} else if tt.enableOOB {
				// Legacy mode - should create interactsh client
				assert.True(t, tt.expectClient)
			}
		})
	}
}
